---

services:
  dummy-spa:
    container_name: dummy-spa
    build:
      context: ./src/client
      dockerfile: ../../build/images/client/Dockerfile
      target: production
    environment:
      NODE_ENV: $DUMMY_SPA_NODE_ENV
      VUE_APP_API_URL: $DUMMY_API_URL
    volumes:
      - ./src/client/src:/home/node/app/src:rw
    ports:
      - "${DUMMY_SPA_PORT}:8080"
    networks:
      - dev-ecommpay-pp-network

  dummy-fpm: &server_app
    container_name: dummy-fpm
    build:
      context: ./src/server
      dockerfile: ../../build/images/server/Dockerfile
      target: production
      args:
        UID: 1000
        GID: 1000
    env_file:
      - .env
    depends_on:
      - dummy-rabbit
      - dummy-memcached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/server:/var/www:rw
      - webFront:/var/www/public
    networks:
      - dev-ecommpay-pp-network

  dummy-api:
    container_name: dummy-api
    image: nginx:latest
    environment:
      NGINX_FAST_CGI_PASS: dummy-fpm:9000
      NGINX_ROOT: /var/www/public
    ports:
      - "${DUMMY_API_PORT}:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.dummy_https.rule=Host(`dummy.paymentpage.localhost`) || HostRegexp(`^dummy-paymentpage-[-\d]+\.nip\.io$$`)
      - traefik.http.routers.dummy_https.tls=false
      - traefik.http.routers.dummy_https.entrypoints=http
    volumes:
      - ./build/images/nginx:/etc/nginx/templates
      - webFront:/var/www/public
    links:
      - dummy-fpm
    networks:
      - dev-ecommpay-pp-network

  dummy-callbacks_queue_consumer:
    <<: *server_app
    container_name: dummy-consumer
    restart: on-failure
    entrypoint: ["php", "yii", "queue/listen", $DUMMY_API_CALLBACKS_QUEUE]

  dummy-rabbit:
    container_name: dummy-rabbit
    image: rabbitmq:latest
    networks:
      - dev-ecommpay-pp-network
    environment:
      RABBITMQ_HOST: $DUMMY_RABBITMQ_HOST
      RABBITMQ_DEFAULT_USER: $DUMMY_RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $DUMMY_RABBITMQ_DEFAULT_PASS

  dummy-memcached:
    container_name: dummy-memcached
    networks:
      - dev-ecommpay-pp-network
    image: memcached:latest

  dummy-db:
    container_name: dummy-db
    image: mysql:5.7.42
    networks:
      - dev-ecommpay-pp-network
    environment:
      MYSQL_ROOT_PASSWORD: $DUMMY_DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DUMMY_DB_NAME
      MYSQL_USER: $DUMMY_DB_USER
      MYSQL_PASSWORD: $DUMMY_DB_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DUMMY_DB_EXTERNAL_PORT}:3306"

volumes:
  dbdata:
  webFront:

networks:
  dev-ecommpay-pp-network:
    name: dev-ecommpay-pp-network
    external: true