version: '3.4'

x-environments: &environments
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "app"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "password"
    NODE_ENV: "develop"
    API_URL: "http://localhost:8082"
    CALLBACK_URL: "http://pp.terminal.test"
    PHP_IDE_CONFIG: "serverName=docker"

services:
    client:
        build:
            context: ./src/client
            dockerfile: ../../build/images/client/Dockerfile
        ports:
            - "8083:8080"
        user: "node"
        environment: *environments
        volumes:
            - ./src/client:/home/node/app:rw
        command: "npm run serve"
    nginx:
        build:
            context: ./src/server
            dockerfile: ../../build/images/nginx/Dockerfile
        ports:
            - "8082:80"
        volumes:
            - ./src/server:/var/www
        links:
            - api
    api:
        build:
            context: ./src/server
            dockerfile: ../../build/images/server/Dockerfile
            args:
                UID: 1000
                GID: 1000
        environment: *environments
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "pp.terminal.test:192.168.20.20"
        volumes:
            - ./src/server:/var/www:rw
        links:
            - db
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment: *environments
        volumes:
            - ./build/dump:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
