version: '3.4'

x-environments: &environments
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_PASSWORD: "password"
    MYSQL_DATABASE: "app"
    MYSQL_USER: "user"
    NODE_ENV: "production"
    API_URL: "http://staging01.dev.ru1:8082"
    RABBITMQ_HOST: "rabbit"
    RABBITMQ_DEFAULT_USER: "test"
    RABBITMQ_DEFAULT_PASS: "#HJ@j$$%!Hjd"
    CALLBACKS_QUEUE_NAME: &callback-queue-name "callbacks-queue"
    DISABLE_SENDING_CALLBACKS: "true"
    MEMCACHED_HOST: "memcached"
    MEMCACHED_PORT: 11211

services:
    client:
        image: konstantinpopov/payment-page-mock-client:main
        ports:
            - target: 8080
              published: 80
        environment: *environments
    nginx:
        image: konstantinpopov/payment-page-mock-nginx:main
        volumes: &sharedStatic
            - type: bind
              source: ./assets
              target: /var/www/public/assets
            - type: bind
              source: ./uploads
              target: /var/www/public/uploads
        ports:
            - target: 80
              published: 8082
    api: &server_app
        image: konstantinpopov/payment-page-mock-api:main
        environment: *environments
        volumes: *sharedStatic
    callbacks_queue_consumer:
        <<: *server_app
        restart: on-failure
        entrypoint: ["php", "yii", "queue/listen", *callback-queue-name]
    rabbit:
        image: rabbitmq:latest
        environment: *environments
    memcached:
        image: memcached:latest
    db:
        image: mysql:latest
        ports:
            - target: 3306
              published: 3306
        environment: *environments
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
    static:
