version: '3.4'

services:
    dummy-spa:
        container_name: dummy-spa
        build:
            context: ./src/client
            dockerfile: ../../build/images/client/Dockerfile
            target: development
        environment:
            NODE_ENV: $DUMMY_SPA_NODE_ENV
            VUE_APP_API_URL: $DUMMY_API_URL
        volumes:
            - ./src/client/src:/home/node/app/src:rw
        ports:
            - "${DUMMY_SPA_PORT}:8080"

    dummy-api:
        container_name: dummy-api
        build:
            context: ./src/server
            dockerfile: ../../build/images/nginx/Dockerfile
        ports:
            - "${DUMMY_API_PORT}:80"
        volumes:
            - ./src/server/public:/var/www/public
        links:
            - dummy-fpm

    dummy-fpm: &server_app
        container_name: dummy-fpm
        build:
            context: ./src/server
            dockerfile: ../../build/images/server/Dockerfile
            args:
                UID: 1000
                GID: 1000
        env_file:
            - .env
        depends_on:
            - dummy-rabbit
            - dummy-memcached
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./src/server:/var/www:rw

    dummy-callbacks_queue_consumer:
        <<: *server_app
        container_name: dummy-consumer
        restart: on-failure
        entrypoint: ["php", "yii", "queue/listen", $DUMMY_API_CALLBACKS_QUEUE]

    dummy-rabbit:
        container_name: dummy-rabbit
        image: rabbitmq:latest
        environment:
            RABBITMQ_HOST: $DUMMY_RABBITMQ_HOST
            RABBITMQ_DEFAULT_USER: $DUMMY_RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $DUMMY_RABBITMQ_DEFAULT_PASS

    dummy-memcached:
        container_name: dummy-memcached
        image: memcached:latest

    dummy-db:
        container_name: dummy-db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: $DUMMY_DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DUMMY_DB_NAME
            MYSQL_USER: $DUMMY_DB_USER
            MYSQL_PASSWORD: $DUMMY_DB_PASSWORD
        ports:
            - "${DUMMY_MYSQL_PORT}:3306"
        volumes:
            - ./build/example/dump:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
