version: '3.4'

x-environments: &environments
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "app"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "password"
    NODE_ENV: "develop"
    API_URL: "http://localhost:8082"
    CALLBACK_URL: "http://pp.terminal.test"
    CALLBACK_SECRET: "JYyVXAtQLQ"
    PHP_IDE_CONFIG: "serverName=docker"
    RABBITMQ_HOST: "rabbit"
    RABBITMQ_DEFAULT_USER: "local"
    RABBITMQ_DEFAULT_PASS: "local"
    CALLBACKS_QUEUE_NAME: &callback-queue-name "callbacks-queue"

services:
    client:
        build:
            context: ./src/client
            dockerfile: ../../build/images/client/Dockerfile
            target: development
        volumes:
            - ./src/client/src:/home/node/app/src:rw
        ports:
            - "8083:8080"
    nginx:
        build:
            context: ./src/server
            dockerfile: ../../build/images/nginx/Dockerfile
        ports:
            - "8082:80"
        volumes:
            - ./src/server/public:/var/www/public
        links:
            - api
    api: &server_app
        build:
            context: ./src/server
            dockerfile: ../../build/images/server/Dockerfile
            args:
                UID: 1000
                GID: 1000
        environment: *environments
        depends_on:
            - rabbit
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "pp.terminal.test:192.168.20.20"
        volumes:
            - ./src/server:/var/www:rw
        links:
            - db
    callbacks_queue_consumer:
        <<: *server_app
        restart: on-failure
        entrypoint: ["php", "yii", "queue/listen", *callback-queue-name]
    rabbit:
        image: rabbitmq:latest
        environment: *environments
        ports:
            - "5672:5672"
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment: *environments
        volumes:
            - ./build/dump:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
