version: '3.4'
services:
    server:
        image: nginx:latest
        ports:
            - "8082:80"
        volumes:
            - ./build/hosts:/etc/nginx/conf.d
            - ./runtime/logs/nginx:/var/log/nginx
            - ./src/server:/var/www
        links:
            - php
    client:
        build:
            context: ./src/client
            dockerfile: ../../build/images/client/Dockerfile
        ports:
            - "8083:8080"
        user: "node"
        environment:
            - NODE_ENV=develop
        volumes:
            - ./src/client:/home/node/app:rw
        command: "npm run serve"
    php:
        build:
            context: ./build/images/server
            args:
                UID: 1000
                GID: 1000
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        volumes:
            - ./src/server:/var/www:rw
        links:
            - db
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./build/dump:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "app"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        expose:
            - "3306"
volumes:
    dbdata:
