version: '3.4'

services:
    client:
        build:
            context: ./src/client
            dockerfile: ../../build/images/client/Dockerfile
            target: development
        environment:
            NODE_ENV: $SPA_NODE_ENV
            VUE_APP_API_URL: $API_URL
        volumes:
            - ./src/client/src:/home/node/app/src:rw
        ports:
            - "${SPA_PORT}:8080"

    nginx:
        build:
            context: ./src/server
            dockerfile: ../../build/images/nginx/Dockerfile
        ports:
            - "${API_PORT}:80"
        volumes:
            - ./src/server/public:/var/www/public
        links:
            - api

    api: &server_app
        build:
            context: ./src/server
            dockerfile: ../../build/images/server/Dockerfile
            args:
                UID: 1000
                GID: 1000
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
            YII_ENV: $API_YII_ENV
            YII_DEBUG: $API_YII_DEBUG
            API_URL: $API_URL
            API_CALLBACKS_QUEUE_NAME: $API_CALLBACKS_QUEUE
            API_CALLBACK_URL: $API_CALLBACK_URL
            API_CALLBACK_SECRET: $API_CALLBACK_SECRET
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_PORT: $MYSQL_PORT
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            RABBITMQ_HOST: $RABBITMQ_HOST
            RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
            MEMCACHED_HOST: $MEMCACHED_HOST
            MEMCACHED_PORT: $MEMCACHED_PORT
        depends_on:
            - rabbit
            - memcached
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "pp.terminal.test:192.168.20.20"
        volumes:
            - ./src/server:/var/www:rw
        links:
            - db

    callbacks_queue_consumer:
        <<: *server_app
        restart: on-failure
        entrypoint: ["php", "yii", "queue/listen", $API_CALLBACKS_QUEUE]

    rabbit:
        image: rabbitmq:latest
        environment:
            RABBITMQ_HOST: $RABBITMQ_HOST
            RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS

    memcached:
        image: memcached:latest

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./build/example/dump:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
