version: '3.4'

services:
    client:
        image: konstantinpopov/dummy-spa:main
        ports:
            - "${DUMMY_SPA_PORT}:8080"
        environment:
            NODE_ENV: $DUMMY_SPA_NODE_ENV
            VUE_APP_API_URL: $DUMMY_API_URL

    nginx:
        image: konstantinpopov/dummy-api:main
        volumes: &sharedStatic
            - type: bind
              source: ./runtime/assets
              target: /var/www/public/assets
            - type: bind
              source: ./runtime/uploads
              target: /var/www/public/uploads
        ports:
            - "${DUMMY_API_PORT}:80"

    api: &server_app
        image: konstantinpopov/dummy-fpm:main
        volumes: *sharedStatic
        env_file:
            - .env

    callbacks_queue_consumer:
        <<: *server_app
        entrypoint: ["php", "yii", "queue/listen", $DUMMY_API_CALLBACKS_QUEUE]

    rabbit:
        image: rabbitmq:latest
        environment:
            RABBITMQ_HOST: $DUMMY_RABBITMQ_HOST
            RABBITMQ_DEFAULT_USER: $DUMMY_RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $DUMMY_RABBITMQ_DEFAULT_PASS

    memcached:
        image: memcached:latest

    db:
        image: mysql:latest
        ports:
            - "${DUMMY_MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: $DUMMY_MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $DUMMY_MYSQL_DATABASE
            MYSQL_USER: $DUMMY_MYSQL_USER
            MYSQL_PASSWORD: $DUMMY_MYSQL_PASSWORD
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
    static:
