version: '3.4'

x-environments: &environments
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_PASSWORD: "password"
    MYSQL_DATABASE: "app"
    MYSQL_USER: "user"
    API_URL: "http://staging01.dev.ru1:8082"
    NODE_ENV: "production"

services:
    client:
        image: konstantinpopov/payment-page-mock-client:main
        ports:
            - target: 8080
              published: 80
        environment: *environments
    nginx:
        image: konstantinpopov/payment-page-mock-nginx:main
        volumes:
            - static:/var/www/public
        ports:
            - target: 80
              published: 8082
    api:
        image: konstantinpopov/payment-page-mock-api:main
        environment: *environments
        volumes:
            - static:/var/www/public
    db:
        image: mysql:latest
        ports:
            - target: 3306
              published: 3306
        environment: *environments
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
    static:
