<?php

namespace App\Stub\Session;

use App\Stub\Collection\ArrayCollection;

class State
{
    /**
     * @var string Unique request id generated by mock
     */
    private string $requestId;

    /**
     * @var int Route identity detected at sale request
     */
    private int $routeId;

    /**
     * @var array Initial request body
     */
    private array $initialRequest;

    /**
     * @var int Indicates position of next available collection callback
     */
    private int $cursor = 0;

    private array $actions = [];

    /**
     * @param string $requestId
     * @param int $routeId
     * @param array $initialRequest
     */
    public function __construct(string $requestId, int $routeId, array $initialRequest)
    {
        $this->requestId = $requestId;
        $this->routeId = $routeId;
        $this->initialRequest = $initialRequest;
    }

    public function getRequestId(): string
    {
        return $this->requestId;
    }

    public function getRouteId(): int
    {
        return $this->routeId;
    }

    public function getInitialRequest(): ArrayCollection
    {
        return new ArrayCollection($this->initialRequest);
    }

    public function getCursor(): int
    {
        return $this->cursor;
    }

    public function next(): void
    {
        $this->cursor += 1;
    }

    public function registerAction(string $key): self
    {
        if (!isset($this->actions[$key])) {
            $this->actions[$key] = false;
        }

        return $this;
    }

    public function completeAction(string $key): self
    {
        $this->actions[$key] = true;

        return $this;
    }

    public function isActionCompleted(string $key): bool
    {
        return $this->actions[$key] ?? false === true;
    }

    public function isActionRegistered(string $key): bool
    {
        return isset($this->actions[$key]);
    }
}
