on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup Docker Build-x
        id: build-x
        uses: docker/setup-buildx-action@v1

      - name: Build and push application fpm image
        uses: docker/build-push-action@v3
        with:
          context: src/server
          file: build/images/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/dummy-fpm:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            UID=1000
            GID=1000

      - name: Build and push SPA image
        uses: docker/build-push-action@v3
        with:
          context: src/client
          file: build/images/client/Dockerfile
          target: production
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/dummy-spa:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push nginx server image
        uses: docker/build-push-action@v3
        with:
          context: src/server
          file: build/images/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/dummy-api:${{ steps.get_version.outputs.VERSION }}
