on:
  push:
    branches: [main]
jobs:
  build-server:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup Docker Build-x
        id: build-x
        uses: docker/setup-buildx-action@v1

      - name: Build and push API image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src/server
          file: build/images/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/payment-page-mock-api:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            UID=1000
            GID=1000

