on:
  push:
    branches: [main]
jobs:
  test:
    name: Test server application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test

  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup Docker Build-x
        id: build-x
        uses: docker/setup-buildx-action@v1

      - name: Build and push server image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: src/server
          file: build/images/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/payment-page-mock-server:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            UID=1000
            GID=1000
